[package]
name = "WebAPIAxticRust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde_json = "=1.0.1"
serde = "1.0.197"
env_logger = "0.11.3"
dotenv = "0.15.0"
lazy_static = "1.5.0"
